# Generated by Django 2.2.7 on 2020-03-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200315_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
