# Generated by Django 2.2.7 on 2020-03-16 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20200315_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('pic', models.ImageField(upload_to='upload_images')),
                ('desc', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('numUnits', models.IntegerField()),
                ('emptyUnit', models.IntegerField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotels')),
            ],
        ),
    ]
