# Generated by Django 2.2.7 on 2020-03-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
