# Generated by Django 2.2.7 on 2020-03-19 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_days', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_num', models.CharField(max_length=64)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.units')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
