# Generated by Django 2.2.7 on 2020-03-19 20:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0009_book_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='books',
        ),
    ]
