# Generated by Django 2.2.7 on 2020-03-19 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_num',
            new_name='order_number',
        ),
    ]
