# Generated by Django 2.2.7 on 2020-03-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20200319_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=64),
        ),
    ]
