# Generated by Django 2.2.7 on 2020-03-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_user_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_information',
            old_name='user',
            new_name='user_id',
        ),
    ]
