# Generated by Django 2.2.7 on 2020-03-22 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20200321_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 16, 49, 6, 399738)),
        ),
        migrations.AddField(
            model_name='books',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 16, 49, 6, 399738)),
        ),
    ]
