# Generated by Django 2.2.7 on 2020-03-23 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20200322_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 18, 34, 32, 253031)),
        ),
        migrations.AlterField(
            model_name='books',
            name='num_of_days',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='books',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 23, 18, 34, 32, 253031)),
        ),
    ]
