# Generated by Django 2.2.7 on 2020-03-24 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20200323_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='lat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='longtude',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='from_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 24, 14, 26, 37, 957841)),
        ),
        migrations.AlterField(
            model_name='books',
            name='to_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 24, 14, 26, 37, 957841)),
        ),
    ]
